module.exports = [
  'react',
  'react-dom',
  'react-router',
  'react-router-dom',
  'react-tap-event-plugin',
  'material-ui',
  'trim',
  'rxjs',
  'redux-form',
  'redux',
  'firebase',
  'react-router-redux',
  'redux-immutable',
  'redux-observable',
  'react-redux',
  'immutable',
];
